### ISSUE TITLE
Make segments optional

### ISSUE THREAD

**Issue by ignasi35** [asyncapi/topic-definition#3]
I think the current definition helps a developer to separate messages but it can also be missleading a novice developer into creating topics too granular.

> hitch.accounts.1.0.event.user.signup

I think all segments after version should be made optional. This has the advantage of providing ordering so that I can consume all events published by `hitch.accounts.3` in the order they were emited. Using the current approach I'd have to subscribe to several topics  `hitch.accounts.1.0.event.xxx.yyy` and do my best when the message are reordered.

**Comment by fmvilas** [comment]
Thanks for your feedback @ignasi35. What you say makes sense but just let me give you a bit of context around it. This is not actually part of AsyncAPI specification and not even near to be a specification. We left the repo here in case it could help someone, but we created it just for internal use at Hitch.

That being said, we bet for a more strict way of defining the topics because it enables us to create better tooling around it. About the example you gave me regarding reordering, we don't need that. We actually don't care about order, but if at some point we would need it, I would use headers or payload to add this piece of information, instead of adding it to the topic.

As an example, we thought on putting the version number also in the headers or in the payload, but that would make it harder (or even impossible) for us to select which messages we want to receive and which not.

Does it make sense?
